### ISSUE TITLE
User profile error when twitter username is unicode symbols only

### ISSUE THREAD

**Issue by juanmnl** [TelescopeJS/Telescope#1055]
Tried several variations, but when a twitter user registers with a unicode-symbols-only username (ex. ⦿⦿⦿⦿⦿) the slug returns undefined on the console, and when accessed through the users panel, the url shows (with a blank page):
![screen shot 2015-07-03 at 7 15 51 pm](https://cloud.githubusercontent.com/assets/699945/8505811/3a54600e-21b9-11e5-832a-90d2ac8eef85.png)

When this happens, the recently registered user doesn't have access to the 'view profile' and 'edit profile' on the user dropdown.

![telescp-err](https://cloud.githubusercontent.com/assets/699945/8505824/d7d4acda-21b9-11e5-90b8-9985f800aac0.gif)

I don't know if this should be fixed or if it will be better not using twitter username for the slug at all, as it's editable and could be easily duplicated.

**Comment by SachaG** [comment]
This is because the user profile slug is calculated based on the Twitter display name, not the Twitter handle: 

https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-users/lib/callbacks.js#L106-L107

There's actually a couple problems with this. First the one you pointed out, but also the fact that two Twitter users can have the same display name, meaning they'd have the same slug. 

So it sounds like we need to make the slug generation logic a lot smarter. I wonder if that's something that should be included in useraccounts? cc @splendido

**Comment by splendido** [comment]
I'm happy to take suggestion for new features on the [v2.0 trello board](https://trello.com/b/NWHVV4ZA/useraccounts-2-0-roadmap) ;-)

**Comment by xavcz** [comment]
Hey, @juanmnl! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
