### ISSUE TITLE
Voting styles not working

### ISSUE THREAD

**Issue by davedg629** [TelescopeJS/Telescope#1073]
When I upvote a post, it doesn't show the "checkmark" icon. You can see this in action here - http://www.timferrissfanclub.com/

I see that the "voted" and "upvoted" classes are being added, but there doesn't seem to be any css associated with those classes. I'm looking at the [Telescope demo](http://demo2.telescopeapp.org/) and I can see that different classes are added to different elements when something is upvoted, so I'm guessing this is the result of the most recent Telescope update.

**Comment by SachaG** [comment]
This is kind of an edge case. The "upvoted" button gets highlighted using your highlight color, but you happen to have picked black, which is why you can't see the highlight. I would suggest either picking a different color, or else adding some extra CSS just for this. 

(the demo is running an older version that works a little differently, I changed it when I introduced the downvoting option)

(p.s. I'm a Tim Ferris fan as well ;) )

**Comment by davedg629** [comment]
Ahhh, gotcha. Can't believe I missed that. Thanks Sacha, gotta love TFerris!

**Comment by davedg629** [comment]
One more thing - is there a reason that the upvote symbol isn't changing to a check mark?

**Comment by SachaG** [comment]
Yes, with the introduction of the downvote option I decided to stick to colors to highlight voted/ not voted. Otherwise it got confusing.

**Comment by davedg629** [comment]
Gotcha, thanks.
