### ISSUE TITLE
Login button displays empty frame on fresh install

### ISSUE THREAD

**Issue by octohedron** [TelescopeJS/Telescope#1463]
![Image](http://i.imgur.com/G3zV2U3.png)

Steps to reproduce

- Clone this repo
- npm i
- meteor
- go to http://localhost:3000 and press login

Tried reverting to react 15.0.2 as suggested in #1390 => #1384 

Console only shows a warning 

```
WARNING: npm peer requirements (for reactrouter:react-router-ssr) not installed:
 - react-router@3.0.0-beta.1 installed, react-router@2.x needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies
```

The problem could have been introduced in a recent commit, tried a different version around 10 days ago and it worked

**Comment by xavcz** [comment]
Yeah we noticed that as well! The problem comes from the latest updates of `react-bootstrap`: while working on the dropdown something got broken (see [changelog](https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md)).

I updated devel to force the use of v0.30.3 (https://github.com/TelescopeJS/Telescope/commit/eb98fb01997a9ea41af6fdea08fb49f42621b2c8) . You can pull the latest version and checkout on devel.

Or else typing `npm install --save --save-exact react-bootstrap@0.30.3` !

By the way, the react-router warning shouldn't bother, it's just that `reactrouter:react-router-ssr` meteor package wants the v2 of react-router, we are using the v3 because of some useful api 👍  This warning doesn't break anything.

And you should stay on the latest version of react :)
