### ISSUE TITLE
react-router@2.x

### ISSUE THREAD

**Issue by elliotlepers** [TelescopeJS/Telescope#1468]
Quand je lance meteor après avoir terminé l'installation, j'ai une erreur 

WARNING: npm peer requirements (for reactrouter:react-router-ssr) not installed:
- react-router@3.0.0-beta.1 installed, react-router@2.x needed

Et quand j'accède tout de même à l'app, la view de connexion ne se charge pas, quand j'inscris une adresse email à la newsletter, j'obtiens une erreur 500.

Avez-vous une idée ?

**Comment by xavcz** [comment]
Hey Elliot,

For the login form that doesn't shows up, it's a problem caused by the latest version of `react-bootstrap`, check out on `devel` branch, we've forced the use of the latest "functionning" version.

For the newsletter email throwing an error, you need to fill your mailchimp credentials in the settings file (`(sample_)settings.json` and start the app with it: `meteor --settings settings.json`.

The `react-router` warnings are completely normal, it's just a word of warning, nothing terrible: https://github.com/thereactivestack/meteor-react-router-ssr/pull/86

ps: je parle français aussi, mais je pense qu'il vaut mieux s'écrire en anglais pour les autres personnes qui passent par ici 😉
