### ISSUE TITLE
Problem when trying to get packages without local copy

### ISSUE THREAD

**Issue by beeva-manuelastorga** [TelescopeJS/Telescope#1493]
Hi,

I'm starting a new project where we want to try telescope, but we do not want to have the packages on our repo, just do a clean install using meteor's repo

When trying to get packages from meteor repository it comes with several incompatibilities errors, for example:

Mostly all packages of nova are branded on this version with 0.27.3 but meteors goes and says that the latest version on their packages is 0.26.3

Also with nova-forms is even worst, it comes that the latest is 0.25.7

I tried to adjust the versions to 0.26.3 but then the npm dependencies doesn't match with what is needed, wrong versions of react mostly.

So, could you help me on this one? I guess the solution for the problem would be upload and refresh the packages on meteor's "npm" (sorry I'm new to meteor, coming from Node world)

Looking forwards to your comments.

Thank you very much in advance

**Comment by SachaG** [comment]
You're right, we need to publish new versions of the packages, sorry about that!

**Comment by xavcz** [comment]
Packages are published on Atmosphere with version 0.27.3 👍  Thanks for the heads up @beeva-manuelastorga!

However, you shouldn't use from Atmosphere `nova:kadira`: it's the only one that couldn't be published because of the binary dependency. Btw, it's also causing errors when deploying because of the binary.

**Comment by beeva-manuelastorga** [comment]
Hi,

Thanks for answering so fast 👍  :)

I just tried to download the packages again, but still getting the same error:

```
...
....
error: Potentially incompatible change required to top-level dependency:
   nova:core 0.26.3-nova, was 0.27.3-nova.
   Constraints on package "nova:core":
   * nova:core@0.26.3-nova <- nova:users 0.26.3-nova
....
...
```

Already deleted all local folder, even tried deleting everything and did it from scratch and got the same results

Would you please enlighten me?

Looking forward to your comments.

Thanks in advance!

**Comment by xavcz** [comment]
That's weird, they got successfully published last time. 

I think it's better to clone the repo and do your stuff from there, mainly because of the dependencies order and that nova:lib overwrite meteor new project default packages: https://github.com/TelescopeJS/Telescope/blob/master/packages/nova-lib/package.js
