### ISSUE TITLE
Too much UI activity after response to a comment 

### ISSUE THREAD

**Issue by ryw** [TelescopeJS/Telescope#150]
We'll investigate if there's a way to smooth out the UI after posting a reply to a comment.

**Comment by xavcz** [comment]
Hey folks! Thanks for having investigated like that back in the time! This bug is fixed now 😄

Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported, I'm closing this issue. You may already know the new version, however I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!
