### ISSUE TITLE
Isn't it better to store likes in the separate polymorphic Likes Collection?

### ISSUE THREAD

**Issue by Praxie** [TelescopeJS/Telescope#714]
An example of Like document: 
```javascript
{
  _id: "..."
  likerId: "..."
  likeableType: "post"
  likeableId: "..."
}
```

**Comment by SachaG** [comment]
Why?

**Comment by Praxie** [comment]
@SachaG, http://code.tutsplus.com/tutorials/essential-meteor-performance-tips--net-35156
Check the 'Arrays and Nested Objects' paragraph.
I really want to find out which way is more efficient so I've created a question topic on stackoverflow: 
http://stackoverflow.com/questions/28064168/where-to-store-users-followings-followers-users-document-of-followings-collect

**Comment by Praxie** [comment]
@SachaG, what if there will be over 1000 elements in the array?

**Comment by SachaG** [comment]
I agree with the answers on Stack Overflow. Since Meteor doesn't have good support for reactive joins yet, storing upvotes in a separate collection would introduce a lot of complexity. If we ever get to a site having thousands of upvotes on each posts and slowing down because of that, it'll always be time to reconsider. 

Thanks for bringing it up though, I wasn't aware of Arunoda's point about nested arrays :)
