### ISSUE TITLE
Embedly creates a video thumbnail for medium articles even when there isn't any video

### ISSUE THREAD

**Issue by kartikluke** [TelescopeJS/Telescope#718]
To reproduce. Try posting `https://medium.com/design-playbooks/designing-the-hiring-process-e0b59f3ee53`. The thumbnail gets the video link and opens an empty lightbox.

**Comment by SachaG** [comment]
Yes, that's because right now Telescope just displays whatever `iframe` it gets from Embedly. I wonder if we shouldn't think about better video integration, so that the video stops when you close the lightbox for example. We could even have playlists and prev/next video controls.

Anyway for now I guess we can start by fixing this, shouldn't be too hard to check if the contents of the iframe actually are a video or not :)

**Comment by kartikluke** [comment]
Yeah what is the logic for setting a thumbnail to be a video lightbox?

I think this project is the way to go for better video integration: https://github.com/embedly/player.js/

**Comment by kartikluke** [comment]
Related: #710

**Comment by xavcz** [comment]
Hey, @kartikluke! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported, I'm closing this issue. 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍
