### ISSUE TITLE
Facebook-style news feed UI

### ISSUE THREAD

**Issue by vonwao** [TelescopeJS/Telescope#764]
How hard would it be to create a Facebook-style news feed UI?

I'm interested in a UI that's more suited to browsing through stories more easily, without having to click in and out of individual stories.  That mean a longer block of content displayed in the news feed (but not too long), and loading a few comments (most recent or most upvoted).

**Comment by SachaG** [comment]
Showing a longer block of content wouldn't be hard at all. 

On the other hand loading a few comments would be trickier, because comments are not published on the main posts lists by default. So it wouldn't be a big change, but it would require modifying the core to add a `postsListComments` subscription to the `PostsListController` controller.
