### ISSUE TITLE
Newsletter is sent multiple times with same content

### ISSUE THREAD

**Issue by nickhould** [TelescopeJS/Telescope#776]
Since February 15, I've been sending the same newsletter over and over again (almost everyday). The newsletter has the same exact content.

My newsletter is scheduled to be sent on Monday/Thursday.

The application I'm running no longer takes into account:
* A post cannot be sent twice via email to a user
* The newsletter must respect the schedule set in the settings.

**Comment by john-henry** [comment]
I have just started seeing this exact same behaviour since I upgraded to latest.
I have a 3 day schedule and it now seems to be sending same content every day

**Comment by jshimko** [comment]
Interesting.  I have a weekly sending on Mon and it works fine.

**Comment by SachaG** [comment]
I've heard that from a couple people. I'll look into it.

**Comment by SachaG** [comment]
I just fixed a potential issue with HTML email generation on the `devel` branch. Maybe you could pull in the latest changes and give it a try?

Basically with the [juice](https://github.com/Automattic/juice) settings I was using, some of the HTML inlining was failing depending on the newsletter's content. Not sure if it's what was triggering the bug, but it might've been.

**Comment by john-henry** [comment]
Ok there is definitely an issue here. Newsletter sent on Monday, Wed and again today on Thursday. I see the Meta newsletter was sent at the same time.

The other issue is duplicate content which never happened previously either. So if I set a limit of 10 items for my newsletter and between Monday and Wed only have 4 new items, then it uses 6 already sent posts to fill up the newsletter. So rather than a limit of NEW posts it is just compiling newsletter of all 10 latest posts regardless if used in newsletter previously or not.

**Comment by SachaG** [comment]
Are you guys still seeing this issue? @john-henry maybe ping me on the Slack channel next time you see me online so we can work through it together?

**Comment by SachaG** [comment]
Closing this for now, please reopen it if the problem happens again.
