### ISSUE TITLE
Convert the vote system to be more customizable through packages

### ISSUE THREAD

**Issue by Baxter900** [TelescopeJS/Telescope#796]
I recently tried to implement a package that modifies how voting works, and I simply couldn't get it to work. The hooks currently available are insufficient by far.

Currently the hooks available are the upvoteCallbacks and the downvoteCallbacks. At the very least, hooks for cancelUpvote and cancelDownvote need to be available. Those are easy enough to add, but that still leaves packages in an awkward place when modifying voting. Something as simple as modifying vote power is relatively complex. You have to first reformat the code for voting such that it no longer needs to access server variables (such as Meteor.[whatever]), then you need to remove the vote that was added in as part of the normal vote script, and add in the new vote.

The easiest solution I can think of would be to convert the voting system to a package, as that would allow one to copy the package, and disable the original with minimal fuss, or to extend the original package.

**Comment by jshimko** [comment]
I agree that some parts of the voting functionality could be improved upon, but I don't know that I'd consider that a trivial amount of work.  I also don't see many users requesting the ability to modify voting from an external package.  I'm certainly not saying that it's a bad idea (I think it's a great idea!), but it's probably not at the top of the priority list considering how many other things are already on [the roadmap][1].  

Since you feel the current state is "insufficient by far", you are more than welcome to fork the repo and make some contributions.  Pull requests are always welcome.  ;)

[1]: https://trello.com/b/oLMMqjVL/telescope-roadmap

**Comment by Baxter900** [comment]
Haha, yea. It's definitely not a priority for the amount of work it would take to convert it. I actually looked into it as an option when I was working with the feature, as I figured if I could improve upon Telescope there was no reason not to! But the vote system is separated into a lot of different parts. I might put up a pull request for hooks for cancelUpvoteCallback and cancelDownvoteCallback tomorrow, simply because I think that would be relatively easy to do. I might also see if I can re-organize part of the voting code to make modifying the power possible if I have spare time, I have a bit of an idea of how I might do that.

Anyway, sorry if I came off aggressively, that wasn't my intention. I was simply trying to explain the problem I ran into, in case someone wanted to put it on a low priority list, since I didn't see anyone else having mentioned this.

**Comment by Baxter900** [comment]
Umm, quick question. Should I try to preserve backwards compatibility, or aim towards callback names that make sense for the hooks?

**Comment by Baxter900** [comment]
Here's the pull request: https://github.com/TelescopeJS/Telescope/pull/797

**Comment by SachaG** [comment]
Thanks for the PR! Closing this now.
