### ISSUE TITLE
Flash Message don't hide after they're displayed

### ISSUE THREAD

**Issue by capensisma** [TelescopeJS/Telescope#968]
Hello,

So if a flash message like 'Your comment has been deleted.' is shown it will be displayed until user browse another view, it should FadeOut like 4000 milliSec.

thanks

**Comment by SachaG** [comment]
Actually that's kind of by design. We can discuss it but I personally think it's better if error messages don't fade away.

**Comment by foobarbecue** [comment]
Why would you call it a flash then? If it doesn't flash, it's just a small modal ... I need mine to fade away... should be an option because it's a common UI pattern. Android calls it "toast" (because it pops up!) which I think is fun. Anyway, is there an easy way to programmatically dismiss it from inside the app?

**Comment by meteorplus** [comment]
@foobarbecue because it's so fast that you don't notice it, it's THE FLASH
