### ISSUE TITLE
Default Template Breaks in Safari on Mac

### ISSUE THREAD

**Issue by jeremyhodges** [TelescopeJS/Telescope#976]
The default template included with Telescope breaks when you view it with Safari on a Mac. The icon, thumbnail, and all comments stack on top of each other rather than everything being inline.

**Comment by jshimko** [comment]
The layout issue is because Safari requires vendor prefixing for CSS Flexbox features to work.  So that likely means that [Autoprefixer][1] isn't working for some reason (it's supposed to be [included][3] in the [fourseven:scss][2] package that compiles the SCSS files in Telescope's theme packages).  

I'll take a look when I get a chance.  Thanks for reporting the issue.  :)

[1]: https://github.com/postcss/autoprefixer
[2]: https://atmospherejs.com/fourseven/scss
[3]: https://github.com/TelescopeJS/Telescope/blob/master/scss.json#L2

**Comment by jshimko** [comment]
Also, how old is your install of Telescope?  What happens if you go to http://meta.telesc.pe in Safari?  That site works for me in Safari and that's the latest Telescope code running there.  

If you're using Telescope via a git clone, try checking out the devel branch to use the latest code.  Let me know if you see the same issue.

**Comment by jeremyhodges** [comment]
@jshimko I cloned the sample-project 

When I go to http://meta.telesc.pe/ in Safari it does look correct.

**Comment by jshimko** [comment]
Oops.  Looks like that sample project doesn't have [the scss.json][1] that `fourseven:scss` is expecting.  For now, you can try cloning [the devel branch][2] for the latest updates.  (and we'll add the scss.json to the theme packages)

[1]: https://github.com/TelescopeJS/Telescope/blob/devel/scss.json
[2]: https://github.com/TelescopeJS/Telescope/tree/devel

**Comment by jeremyhodges** [comment]
@jshimko Just to confirm, I cloned to devel branch and pushed to meteor.com and everything is well: http://tbk-grow.meteor.com/

**Comment by jshimko** [comment]
Thanks!
