### ISSUE TITLE
In Users page "Make Admin" button does nothing. 

### ISSUE THREAD

**Issue by ashrestha8** [TelescopeJS/Telescope#992]
I want to delete the first created user who is admin, then disable email register, otherwise Admin is not able to log in.

**Comment by capensisma** [comment]
It does work, i guess you have an older version of telescope.

**Comment by SachaG** [comment]
While it does work for me as well in the latest version of Telescope, you never know, there could be a bug. I guess the first step would be knowing what version @ashrestha8 is running?

**Comment by ashrestha8** [comment]
Sorry, I am not too sure where to find information about the version. I have used a one click deploy to heroku, yesterday

**Comment by SachaG** [comment]
Just open up your console and type `Telescope.VERSION`. Or give us the link to your site?

**Comment by ashrestha8** [comment]
It's http://howtostartup.doersapp.co

**Comment by jshimko** [comment]
@ashrestha8 I'd be happy to log in and take a look at it if you shoot me a private message with some admin login credentials.

jeremy dot shimko @ gmail

**Comment by jshimko** [comment]
I also see a few websocket errors in the console.  I suspect there's possibly something wrong on the Heroku end as well.

**Comment by ashrestha8** [comment]
sorry it took some time, have sent you an email

**Comment by jshimko** [comment]
I'm getting the following in the console when trying to make a user an admin on your site:
```
update failed: Access denied undefined
```
And I'm getting the following websocket error regularly whether I'm doing anything or not.
```
WebSocket connection to 'ws://howtostartup.doersapp.co/sockjs/093/hbc84azt/websocket' failed: Error during WebSocket handshake: Unexpected response code: 503
```
There's clearly an issue with websockets (which I assume is a Heroku problem since it doesn't happen anywhere else) and that's likely why you're having the issue.  If possible, I'd try deploying with one of the [other methods][1] until someone is able to figure out the issue with Heroku.  I personally have never used Heroku for a Meteor app, so I may not be the best person to ask for that one.   

[1]: http://telescope.readme.io/v0.20/docs

**Comment by ashrestha8** [comment]
Thanks a lot Jeramy! Maybe will try to deploy with meteor, but hopefully someone will have a heroku option as its much easier!
Anyways thanks for your time!

**Comment by SachaG** [comment]
You could also try updating/redeploying the app on Heroku to use the latest version?
